preprocessing sandboxing
HSE-JetBrains-department/code_search pull request #2
Opened 2022-01-29 08:09 UTC by MassterMax

-add preproc to extract data from source code
-update readme

2022-01-30 07:25 UTC, MassterMax commented
Я добавил хороший экстрактор (даже с заявкой на обработку не только питона)
Кажется, баквит можно будет удалить, если этот пр вмерджим.

2022-01-31 08:31 UTC, MassterMax commented
Добавит примитивный юниттест + расширил мейфайл, чтобы локально тестить эластик. Собираюсь с помощью тестов настроить хороший маппинг и поисковые запросы

2022-01-31 11:01 UTC, Ksenia-C commented on .gitignore
> +.idea/workspace.xml
Остались еще файлы из .idea
Предлагаю написать 
.idea/*

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/cmd/run.py
> +sys.path.insert(0, './')
Эта строчка больше не нужна

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +# from preprocess.mappers.files import extract_class_identifiers_from_file
лишние комментарии

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +        assert lang.value in LANGUAGES, f"language not supported: {lang.value}"
если здесь программа упадет, скорее хотелось бы продолжить обрабатывать репы

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +            data['location'] = f'https://github.com/{repo}/blob/main/{file}'
здесь нужно будет писать не main, а hash коммита

2022-01-31 11:01 UTC, Ksenia-C commented on .gitignore
> +.idea/
.idea/*

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/es/client.py
> +                # for url in data:
скорее можно удалить этот старый код

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +        GitSource(repositories_path)
через ручную загрузку + FolderSource работает быстрее, чем GitSource
можно как минимум добавить возможность обрабатывать через Folder

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +                    docstring = docstring.replace("  ", " ")
чтобы избавиться от пробельной подпоследовательности запустить дважды такую замену недостаточно

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +    # path = "/mnt/c/Users/maxma/Documents/tmp"
здесь нужен этот коментарий?

2022-01-31 11:01 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +        assert lang.value in LANGUAGES, f"language not supported: {lang.value}"
поэтому как мне кажется, лучше продолжить с сообщением об ошибке

2022-01-31 11:04 UTC, MassterMax commented on codesearch/cmd/run.py
> +sys.path.insert(0, './')
А у меня без нее не запускается как раз)) Не знаю, почему

2022-02-01 05:29 UTC, MassterMax commented on codesearch/preproc/extract.py
> +            data['location'] = f'https://github.com/{repo}/blob/main/{file}'
Окей, буду писать тогда последний коммит

2022-02-01 06:03 UTC, MassterMax commented
Порефакторил экстрактор, решу вопрос с тем, как хранить json-файлы и можно будет запускать

2022-02-01 09:00 UTC, Ksenia-C commented on codesearch/cmd/run.py
> +sys.path.insert(0, './')
literally me a week ago
Если с PyCharm, то в настойках configurations (как-то так) нужно поставить checkbox в строчке "Add content roots to PYTHONPATH"

Если запускаешь с терминала, то надо написать:
PYTHONPATH=./ python3 codesearch/cmd/run.py command ...

2022-02-01 09:00 UTC, Ksenia-C commented on .gitignore
> +.idea/*
что-то файлы не открепились ниже. Возможно нужно сделать 
git reset --soft HEAD~1
git reset .
git add .
git commit -m ""
git push -f

2022-02-01 09:00 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +                el['location'] = f'{url}/blob/{repo.commit()}/{el["location"]}'
в файле есть hash нужного коммита, в commit_sha

2022-02-01 09:00 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +            print('success!\n')
По идее эта строчка не особо имеет смысл, если не выводить какую-нибудь информацию о репозитории

2022-02-01 09:00 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +    print(f"the whole process took {time.time() - t} seconds with {exceptions} exceptions")
скорее интересно время когда закончилась обработка, чем сколько заняло. И опять же - с какой-нибудь информацией о репозитории (аля название)

2022-02-01 09:17 UTC, MassterMax commented on codesearch/preproc/extract.py
> +                el['location'] = f'{url}/blob/{repo.commit()}/{el["location"]}'
он otdated

2022-02-01 09:18 UTC, MassterMax commented
Сделал так, что порождаются несколько джсонов. Порефакторю и можно запускать на машинке обработку

2022-02-01 09:18 UTC, MassterMax commented
Параллельно обработке буду писать маппинг и запросы

2022-02-01 09:21 UTC, MassterMax commented
Удалил файлы идеи из коммита

2022-02-01 09:22 UTC, MassterMax commented on codesearch/preproc/extract.py
> +    print(f"the whole process took {time.time() - t} seconds with {exceptions} exceptions")
с какой? я просто пишу, что текущий репо удачно обработался - альтернатива - выведется эксепшн, если что-то упало

2022-02-01 09:23 UTC, MassterMax commented on codesearch/preproc/extract.py
> +            print('success!\n')
с какой? я просто пишу, что текущий репо удачно обработался - альтернатива - выведется эксепшн, если что-то упало

2022-02-01 09:23 UTC, MassterMax commented on codesearch/preproc/extract.py
> +    print(f"the whole process took {time.time() - t} seconds with {exceptions} exceptions")
это инфа обо всех обработанных репозиториях. Ок, выведу, сколько сейчас время))

2022-02-01 09:37 UTC, Ksenia-C commented
Например имя репозитория. Я могу ошибаться, но сейчас не понятно, какой
репозиторий обрабатывается с success, а какой с ошибкой

вт, 1 февр. 2022 г. в 12:23, MassterMax ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In codesearch/preproc/extract.py
> <https://github.com/HSE-JetBrains-department/code_search/pull/2#discussion_r796401782>
> :
>
> > +
>
> +            print(f"processing: {url}")
>
> +            repo = Repo.clone_from(url, repo_path)
>
> +
>
> +            data = extract_data(temp_path)
>
> +            for el in data:
>
> +                el['location'] = f'{url}/blob/{repo.commit()}/{el["location"]}'
>
> +                el['stargazers_count'] = row['stargazers_count']
>
> +                el['repo_id'] = row['repo_id']
>
> +
>
> +            # data[DATA_KEY].append(extract_data(path)[DATA_KEY])
>
> +            with open(f'{_output_directory}/{owner}_{name}.json', 'w') as fp:
>
> +                json.dump(data, fp)
>
> +
>
> +            shutil.rmtree(repo_path)
>
> +            print('success!\n')
>
>
> с какой? я просто пишу, что текущий репо удачно обработался - альтернатива
> - выведется эксепшн, если что-то упало
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/HSE-JetBrains-department/code_search/pull/2#discussion_r796401782>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH745QBMLYPWO6DE5QLMH7TUY6RBDANCNFSM5NCS6RFA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-02-04 20:06 UTC, Ksenia-C commented on README.md
> +PYTHONPATH=./ python3 codesearch/cmd/run.py extract /mnt/c/Users/maxma/Documents/GitHub/code_search/codesearch/preproc/repositories.csv /mnt/c/Users/maxma/Documents/ /mnt/c/Users/maxma/Documents/GitH
более читабельно кмк использовать алиас из начала дока и вместо полных путей указывать что-нибудь сокращенное (это чисто про readme)

2022-02-04 20:06 UTC, Ksenia-C commented on .gitignore
> +# buckwheat - remove in future
настало время убрать его

2022-02-04 20:06 UTC, Ksenia-C commented on .gitignore
вообще такое ощущение, что легче просто указать, что не надо игнорить, например
!codesearch/*
!Makefile
!README.md
и тд

2022-02-04 20:06 UTC, Ksenia-C commented on README.md
> +PYTHONPATH=./ python3 codesearch/cmd/run.py %command% %args%
Выше есть алиас, с его помощью команды записываются короче -> проще для понимания

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/cmd/run.py
> +@click.argument("results_path")
@click.argument("output_directory", type=click.Path(exists=True))
И ниже в файле также

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/cmd/run.py
> +            print(f'loading: {filename}')
чтобы понимать, если что-то застопорилось, можно добавить временную метку
start loading at {datetime.now()}

2022-02-04 20:06 UTC, Ksenia-C commented on requirements.txt
> +preprocess>=0.6.4
Этот модуль preprocess не нужен. Добавить
pandas>=1.4.0
cytoolz>=0.10.1
pyarrow>=6.0.1

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/es/vs/v1.py
> +# todo - надо поработать с поиском, сделать фильтрацию, сложный поиск, ранжирование
ненужный комментарий кмк

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +            repo = Repo.clone_from(url, repo_path)
Здесь надо добавить проверку на доступность или поставить timeout. В buckwheat это обрабатывается, думаю там можно найти

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +        print(f"processing: {url}")
чтобы лучше понимать, когда застопорилось, можно поставить timestamp
start processing at {datetime.now()}

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +    cnt = 0
cnt чего?

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +            current_dict_size = len(json.dumps(data_to_write))
добавить перенос строки

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +                # data[DATA_KEY].append(extract_data(path)[DATA_KEY])
это нужный комментарий?

2022-02-04 20:06 UTC, Ksenia-C commented on codesearch/preproc/extract.py
> +    storage_path = "/mnt/c/Users/maxma/Documents"
абсолютный путь, можно заменить на относительный или убрать, если это было для теста

2022-02-07 13:48 UTC, MassterMax commented
+body of function
+пофиксить, что написала Ксения

2022-02-07 14:05 UTC, MassterMax commented
+timeout на скачивание

2022-02-07 15:34 UTC, EgorBu requested changes
Отлично, что запушили первый вариант кода! Давайте теперь итеририроваться и улучшать

2022-02-07 15:34 UTC, EgorBu commented on .gitignore
> +# buckwheat - remove in future
да, давайте удалим

2022-02-07 15:34 UTC, EgorBu commented on .gitignore
>  */buckwheat/identifiers_extractor/parsers/build/*
все про buckwheat - надо удалить

2022-02-07 15:34 UTC, EgorBu commented on .gitignore
>  !codesearch/preproc/buckwheat_output/.gitkeep
почему это тут оказалось? Нигде нет `*.gitkeep`

2022-02-07 15:34 UTC, EgorBu commented on README.md
>  Удалить индекс
Надо добавить описание проекта в начало. `readme` сперва должно объяснить, что делается. А потом уже можно сделать секцию, как запускать. https://github.com/src-d/go-git https://github.com/src-d/sourced-ce как примеры

2022-02-07 15:34 UTC, EgorBu commented on README.md
> +## masstermax
Давай назовем секции по смыслу - пусть они даже краткими будут
```
## Installation
...
## Usage
```

2022-02-07 15:34 UTC, EgorBu commented on README.md
> +```
Давай допишем `shell` после ` ``` `

2022-02-07 15:34 UTC, EgorBu commented on README.md
> +```
`shell`

2022-02-07 15:34 UTC, EgorBu commented on README.md
> +PYTHONPATH=./ python3 codesearch/cmd/run.py init code_index_2
непонятные команды - либо добавить объяснение. либо удалить-перенести

2022-02-07 15:34 UTC, EgorBu commented on codesearch/cmd/run.py
>  def cs():
давайте добавлять докстринги везде

2022-02-07 15:34 UTC, EgorBu commented on codesearch/cmd/run.py
>  def init(index_name: str):
докстринг

2022-02-07 15:34 UTC, EgorBu commented on codesearch/cmd/run.py
> +def put(index_name: str, results_path: str):
докстринги

2022-02-07 15:34 UTC, EgorBu commented on codesearch/cmd/run.py
> +            print(f'loading: {filename}')
давайте консистентно использовать кавычки - везде двойные

2022-02-07 15:34 UTC, EgorBu commented on codesearch/es/client.py
> +class ElasticSearchClient:
докстринги - нужны во всех функциях и классах

2022-02-07 15:34 UTC, EgorBu commented on codesearch/es/search_constructor.py
> +INF = 1000000000
https://www.geeksforgeeks.org/python-infinity/#:~:text=As%20of%202020%2C%20there%20is,to%20represent%20it%20as%20infinity.

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +import json
давайте следовать pep8 c импортами https://www.python.org/dev/peps/pep-0008/#imports

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +def extract_from_csv(_csv_path: str, _storage_path: str, _output_directory: str, _one_file_size: int = 1024):
https://www.python.org/dev/peps/pep-0008/#naming-conventions - надо поправить, чтобы соответствовать pep8

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +    t = time.time()
всю логику со временем вынести из этой функции.  Иначе идет смешение разных сущностей и задач. Можно сделать декоратором

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +                # data[DATA_KEY].append(extract_data(path)[DATA_KEY])
удалить

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +            if i[1].type == 'identifier':
кажется, что это должно определяться для каждого языка

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +            # print(f"language is not supported yet: {lang.value} for file {data['location']}")  # todo for debug
удалить

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +            # print(f"L{level}: {'; '.join([i[1].type + ' ' + get_str(i) for i in identifiers])}")  # todo for debug
удалить все закомментированные строчки кода

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +    storage_path = "/mnt/c/Users/maxma/Documents"
надо сделать аргументом - иначе у меня никогда не получится запустить код без модификаций самого кода)

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/extract.py
> +    extract_from_csv(csv_path, storage_path, directory, 1)
что за магический аргумент 1?

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/languages.py
> +    function_name_level = 1
что за магические цифры?

2022-02-07 15:34 UTC, EgorBu commented on codesearch/preproc/repositories.txt
> +https://github.com/MassterMax/sandbox-course-work
что это?

2022-02-07 15:34 UTC, EgorBu commented on tests/es/client_test.py
> +import unittest
порядок импортов неправильный - посмотри pep8, пожалуйста

2022-02-07 15:34 UTC, EgorBu commented on tests/es/client_test.py
> +# Для работы надо запустить docker эластика - test_env_up
использовать только английские комментарии в коде

2022-02-07 15:34 UTC, EgorBu commented on tests/es/client_test.py
> +# Для работы надо запустить docker эластика - test_env_up
перенести в докстринг класса, чтобы объяснить, что происходит

2022-02-09 05:55 UTC, MassterMax commented on .gitignore
Мне кажется, это антипаттерн)

2022-02-09 05:55 UTC, MassterMax commented on README.md
> +PYTHONPATH=./ python3 codesearch/cmd/run.py extract /mnt/c/Users/maxma/Documents/GitHub/code_search/codesearch/preproc/repositories.csv /mnt/c/Users/maxma/Documents/ /mnt/c/Users/maxma/Documents/GitH
Напишу просто себе об этом

2022-02-09 05:57 UTC, MassterMax commented on README.md
> +PYTHONPATH=./ python3 codesearch/cmd/run.py %command% %args%
В принципе я понял, мб буду через алиас, мб кстати нужно оптимизировать команды, чтобы не передавать так много параметров

2022-02-09 06:02 UTC, MassterMax commented on requirements.txt
> +preprocess>=0.6.4
Что такое pyarrow и зачем это нужно?

2022-02-09 06:15 UTC, MassterMax commented on codesearch/preproc/extract.py
> +            current_dict_size = len(json.dumps(data_to_write))
зачем.

2022-02-09 06:15 UTC, MassterMax commented on codesearch/preproc/extract.py
> +    storage_path = "/mnt/c/Users/maxma/Documents"
это уже есть как аргумент, просто в мейне я для себя тестил

2022-02-09 06:25 UTC, MassterMax commented on README.md
> +```
А что это дало, я не увидел разницы?

2022-02-09 06:26 UTC, MassterMax commented on README.md
> +```
В смысле в pycharm увидел, но на отрисовке md-файла ничего не поменялось

2022-02-09 06:28 UTC, MassterMax commented on codesearch/cmd/run.py
> +            print(f'loading: {filename}')
А можно везде одинарные?..

2022-02-09 06:29 UTC, MassterMax commented on codesearch/es/search_constructor.py
> +INF = 1000000000
Прикольно

2022-02-09 06:37 UTC, MassterMax commented on codesearch/preproc/extract.py
> +    t = time.time()
Хотелось это использовать для логирования, чтобы для каждого репозитория логировать время обработки. Как поступить тогда?

2022-02-09 06:39 UTC, MassterMax commented on codesearch/preproc/extract.py
> +import json
А что тут не так, у меня в pycharm PEP-8, все норм вроде...

2022-02-09 06:41 UTC, MassterMax commented on codesearch/preproc/extract.py
> +            if i[1].type == 'identifier':
Что именно? Что название функции - это identifier?

2022-02-09 06:43 UTC, MassterMax commented on codesearch/preproc/languages.py
> +    function_name_level = 1
Это то, что я объяснял на митинге, я для каждого языка делаю шаблон, по которому изымаю identifiers, докстринг, имя функции... У каждого свое дерево, поэтому вот так

2022-02-09 06:46 UTC, MassterMax commented
Немного порефакторил, еще будут коммиты

2022-02-09 06:47 UTC, MassterMax commented
Забыл прописать в коммите - я выпилил buckwheat

2022-02-09 15:13 UTC, MassterMax commented on tests/es/client_test.py
> +# Для работы надо запустить docker эластика - test_env_up
мы типа вообще весь проект пишем на английском?

2022-02-10 14:09 UTC, MassterMax commented
Добавил фиксы от Ксении

2022-02-14 15:01 UTC, MassterMax commented on codesearch/preproc/extract.py
> +    t = time.time()
+ add progress bar

2022-02-14 15:11 UTC, MassterMax commented
- ParquetDumper

2022-03-15 14:15 UTC, MassterMax commented
todo - 
REALISE_SEARCH_MODE заменить на Enum

2022-03-15 14:29 UTC, MassterMax commented
заменить маппинг эластика

2022-03-22 12:39 UTC, EgorBu approved these changes
Let's merge and improve it iteratively

2022-03-22 12:39 UTC, merged